### ISSUE TITLE
Workaround to build _.deb package_ of dump1090-fa 3.6.3 _Without bladeRF, on armhf & amd64_

### ISSUE THREAD

**Issue by abcd567a** [jprochazka/adsb-receiver#473] opened 2018-10-13 14:43 UTC
# Workaround to build dump1090-fa 3.6.3 "deb package" _Wihout bladeRF_ on _armhf and amd64_

This method is based on the method posted by [**wiedehopf** in Flightaware Forums](https://discussions.flightaware.com/t/cannot-install-piaware-on-orange-pi-zero-plus-allwinner-h5-arm64/37068/9)

I tried it successfully on **x64 machine (Intel PC)**
- **Debian 9.5 (stretch) amd64**
- **Ubuntu 18.04 amd64**

On both I could successfully built **amd64 package** as shown below.
.
```
abcd@debian:~$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"

sudo apt install git
git clone https://github.com/flightaware/dump1090.git
Cloning into 'dump1090'...
... ...
... ...

cd dump1090

sudo nano debian/control
#Scroll down till you find the first lines below. 
#Scroll down further to find second line. 
#Delete libbladerf in both lines as shown in red below.
```
![dump-fa-deb-1](https://user-images.githubusercontent.com/28452511/46896924-bccaa180-ce4d-11e8-9d29-36c06f2ff388.png)

```
sudo nano debian/rules
#Scroll down till you find the line shown below. 
#Change BLADERF=yes to BLADERF=no as shown in red. 
```
![dump-fa-deb-2](https://user-images.githubusercontent.com/28452511/46897051-804b7580-ce4e-11e8-84c5-11ab216d301d.png)

```
#Install packages to fulfill dependencies
sudo apt install debhelper dh-systemd librtlsdr-dev libusb-1.0-0-dev 
sudo apt install pkg-config libncurses5-dev lighttpd

#Build the dump1090-fa package
sudo dpkg-buildpackage -b

dpkg-buildpackage: info: source package dump1090-fa
dpkg-buildpackage: info: source version 3.6.3
.... ....
.... ....
.... ....
dpkg-deb: building package 'dump1090' in '../dump1090_3.6.3_all.deb'.
        dpkg-deb -z1 -Zxz -Sextreme --build debian/.debhelper/dump1090-fa/dbgsym-root ..
dpkg-deb: building package 'dump1090-fa-dbgsym' in '../dump1090-fa-dbgsym_3.6.3_amd64.deb'.
        dpkg-deb --build debian/dump1090-fa ..
dpkg-deb: building package 'dump1090-fa' in '../dump1090-fa_3.6.3_amd64.deb'.
 dpkg-genbuildinfo --build=binary
 dpkg-genchanges --build=binary >../dump1090-fa_3.6.3_amd64.changes
dpkg-genchanges: info: binary-only upload (no source code included)
 dpkg-source --after-build dump1090
dpkg-buildpackage: info: binary-only upload (no source included)

#Go out of dump1090 directory, and check:
cd ../
ls
dump1090                dump1090-fa_3.6.3_amd64.buildinfo  dump1090-fa_3.6.3_amd64.deb
dump1090_3.6.3_all.deb  dump1090-fa_3.6.3_amd64.changes    dump1090-fa-dbgsym_3.6.3_amd64.deb

#INSTALL
sudo dpkg -i dump1090-fa_3.6.3_*.deb

#REBOOT 
sudo reboot 
```
.
**Added Receiver marker and Range Rings**

Opened file for editing:
`sudo nano /etc/default/dump1090-fa `

In the line: 
`RECEIVER_OPTIONS="--device-index 0 --gain -10 --ppm 0 --net-bo-port 30005"`

added:
`--lat xx.xxxx --lon yy.yyyy` 

The line became:
`RECEIVER_OPTIONS="--device-index 0 --gain -10 --lat xx.xxxx --lon yy.yyyy --ppm 0 --net-bo-port 30005" `

(used actual latitude and longitude in place of `xx.xxx` and `yy.yyyy`)
.

**Comment by abcd567a** [comment] 2018-10-15 15:38
# Ubuntu 18.04.1 amd64 - dump1090-fa installed by "deb package" built _WITHOUT bladeRF_
![image](https://user-images.githubusercontent.com/28452511/46961124-07c2ff80-d06e-11e8-86d9-8f420a9df143.png)

.
# Debian 9.5 (stretch) amd64 - dump1090-fa installed by "deb package" built _WITHOUT bladeRF_
![image](https://user-images.githubusercontent.com/28452511/46961268-69836980-d06e-11e8-80a7-b30d80245620.png)

**Comment by abcd567a** [comment] 2018-10-15 17:15
### SUGGESTED MODIFICATION (UNTESTED)

Open file ` dump1090-fa.sh ` for editing
`sudo nano adsb-receiver/bash/decoders/dump1090-fa.sh  `


Deleted this whole chunk of code
```
## BUILD AND INSTALL THE BLADERF PACKAGE FROM SOURCE IF NOT INSTALLED

# Check if the needed bladeRF packages are installed.
if [[ $(dpkg-query -W -f='${STATUS}' libbladerf2 2>/dev/null | grep -c "ok installed") -eq 0 ]] || [[ $(dpkg-query -W -f='${STATUS}$

... ... ...
... ... ...
... ... ...

        sudo dpkg -i libbladerf-udev_*.deb
    fi
fi
echo ""

```

.
Add 4 lines starting with `## DELETE REQUIRMENT TO INSTALL bladeRF`, as shown below
```
## BUILD AND INSTALL THE DUMP1090-FA PACKAGE

echo ""
echo -e "\e[95m  Building and installing the dump1090-fa package...\e[97m"
echo ""
if [[ ! "${PWD}" = "${RECEIVER_BUILD_DIRECTORY}/dump1090-fa/dump1090" ]] ; then
    echo -e "\e[94m  Entering the dump1090-fa git repository directory...\e[97m"
    cd ${RECEIVER_BUILD_DIRECTORY}/dump1090-fa/dump1090 2>&1
fi

## DELETE REQUIRMENT TO INSTALL bladeRF
 sed -i 's/, libbladerf-dev//g' ${RECEIVER_BUILD_DIRECTORY}/dump1090-fa/dump1090/debian/control
 sed -i 's/libbladerf1 (>= 0.2016.06),//g' ${RECEIVER_BUILD_DIRECTORY}/dump1090-fa/dump1090/debian/control
 sed -i 's/BLADERF=yes/BLADERF=no/' ${RECEIVER_BUILD_DIRECTORY}/dump1090-fa/dump1090/debian/rules


echo -e "\e[94m  Building the dump1090-fa package...\e[97m"
echo ""
dpkg-buildpackage -b
echo ""
```

**Comment by jtweeder** [comment] 2018-11-07 14:02
For what it is worth I followed the suggested edits and your other edits on install dump1090-fa on bionic.  Install went without any foreseeable problems or errors on Ubuntu 18.04 bionic.  

I am having some hardware issues persist that are causing no signals to be sent and 'No data received from the SDR for a long time, it may have wedged' messages to appear in my system log, but I believe those are probably unrelated to the install issue and may be more related to the fact I am trying to get it to work as a usb passthrough device on a libvirt machine.

**Comment by jprochazka** [comment] 2019-03-02 05:24
Been toying with making this work both last night and tonight...
Honestly sick of trying to make things work with dump1090-fa and bladeRF.

I am not going to script homebrew patches and what not to make third party packages build. I do not have the time nor the drive to fix what other should, especially those who profit off what I am trying to offer the community through free labor.

I am honestly thinking dump1090-fa will become a second class citizen as of v3.x as far as this project is concerned until the paid members of the community who seem to refuse to fix things or give up information on how they made things work on their end offer up a solution to fix the problem.

**Comment by jprochazka** [comment] 2019-03-02 05:45
I do not know...
I spent the last two nights trying to make this work.
This has gone beyond my pay grade.

As of now and into the foreseeable future think of dump1090-fa as a second class citizen as far as this project is concerned. At least until whoever can fix the issue be it either the developers of bladeRF or FlightAware I am done wasting time on it. There are other dump1090 options available so I would recommend sticking with those.

I like how these bladeRF build issues are directed to me not only here but on other sites as well as if I have anything to do with bladeRF or the FlightAware fork of Dump1090. All I try to do is offer a simple interface to run their build commands nothing more...

**Comment by jprochazka** [comment] 2019-03-02 05:49
I do not know...

I spent the last two nights trying to make this work.
This has gone beyond my pay grade.
I have scripted patches, altered commands with no success.
Basically wasted hours I could have spent on v3.x.

As of now and into the foreseeable future think of dump1090-fa as a second class citizen as far as this project is concerned. At least until whoever can fix the issue be it either the developers of bladeRF or FlightAware. Until then I am done wasting time on it. There are other dump1090 options available so I would recommend sticking with those.

I like how these bladeRF build issues are directed to me not only here but on other sites as well as if I have anything to do with bladeRF or the FlightAware fork of Dump1090. All I try to do is offer a simple interface to run their build commands nothing more...

**Comment by jprochazka** [comment] 2019-03-02 06:12
I spent the last two nights trying to make this work. I have had no luck on Raspbian or Debian Stretch. This project is not about fixing third party shortcoming, which is what this apparently is, so I did not go as far as going through all the hacks which may have worked for others even though I did try to script some.

As stated this has gone beyond the scope of the project. I have scripted patches, altered commands with no success. Basically wasted hours I could have spent on v3.x.

I cant even get things to build on Raspbian/Debian Stretch anymore....

As of now and into the foreseeable future think of dump1090-fa as a second class citizen as far as this project is concerned. At least until whoever can fix the issue be it either the developers of bladeRF or FlightAware do so. Until then I am done wasting time on it.

**There are other dump1090 options available so I would recommend sticking with one of those.**

I like how these bladeRF build issues are directed to me not only here but on other sites as well as if I have anything to do with bladeRF or the FlightAware fork of Dump1090. All I try to do is offer a simple interface to run their build commands nothing more...

I know there is a simple solution out there why people are so tight lipped is beyond me.

I will gladly and with no remorse mark this issue as "wontfix" until someone shows me where the scripts are the cause of the issue or show me a solution which does not require my scripts patching third party source code in order to make things build.

**Comment by abcd567a** [comment] 2019-03-02 06:40
If I recall correctly, when I complained in FA Forum about failure to build dump1090-fa by "adsb-receiver project scripts", Oliver has mentioned "...he is using wrong version of bladeRF". I just now tried to locate it, but could not. Will try to search again.

**Comment by jprochazka** [comment] 2019-03-02 07:33
Tried the package supplied with Raspbian/Debian bladerf (0.2014.09~rc2-5) and the latest from their repository located at https://github.com/Nuand/bladeRF (the 2018 releases) with no luck. If I could get an answer as to what version works I would gladly pull said source code to build.

**Comment by abcd567a** [comment] 2019-03-02 07:37
Oliver did not tell which is the correct version, but gave the hint that the version being used is wrong one

**Comment by abcd567a** [comment] 2019-03-02 07:42
Joe, I have sent you a pm with some info about graphs in Flightaware forum.

**Comment by jprochazka** [comment] 2019-04-19 14:50
The bladeRF issue should be fixed.
Refer to issue #500

**Closed by jprochazka** 2019-04-19 14:50 UTC
Labels: wontfix
