### ISSUE TITLE
existing Blog posts get deleted on update of the portal (the empty default file gets written)

### ISSUE THREAD

**Issue by hasselk** [jprochazka/adsb-receiver#158] opened 2016-04-15 15:03 UTC
the same is true for "Aggregate Site Settings" or any other configuration.
This behaviour should be changed, or at least show a warning about it.

**Comment by jprochazka** [comment] 2016-04-15 15:43
Beginning with v2.0.0 the overwrite issue will no longer happen. In the past with each upgrade the XML data had to be backed up then restored and modified if new values were added. This was the nature of the beast at the time but as data has become more relevant to the system this needed to change.

From v2.0.0 forward the installer in each release will handle any updates to the data automatically and will retain any existing data. Between releases patches will be released so going through the installation process for minor fixes will no longer be needed.

This is actually a duplicate of issue #98.

**Closed by jprochazka** 2016-04-15 15:43 UTC
Labels: duplicate

**Comment by hasselk** [comment] 2016-04-15 16:09
thank you for clarification, i was just iritated because i downloaded the actual master 2 hours ago and run an update, which killed my xml ;)
