### ISSUE TITLE
Aircraft message rate does not generate graph

### ISSUE THREAD

**Issue by Calimerorulez** [jprochazka/adsb-receiver#255] opened 2016-10-05 12:19 UTC
I saw that the Aircraft message rate graph 'dump1090-localhost-aircraft_message_rate-24h.png' isn't being generated on my system. Same goes for other periods of time.

Running the command to generate the graph directly (sudo bash /home/radar/adsb-receiver/build/portal/graphs/make-collectd-graphs.sh 24h) gives me the following error:

ERROR: don't understand 'rate-provisional,0,IF'

Which corresponds to  "CDEF:rate=aircrafts,0,GT,rate-provisional,0,IF"   in build/portal/graphs/make-collectd-graphs.sh on line 55.

Is there any way I can get this to work? I'm not really familiair with rrd... My installed rrdtool version is 1.5.5

**Comment by jprochazka** [comment] 2016-10-11 19:08
dump1090-mutability or dump1090-fa?

**Comment by Calimerorulez** [comment] 2016-10-13 15:30
Dump1090-mutability

**Comment by jprochazka** [comment] 2016-10-17 20:17
This is code that has not changed in quite some time...

Make sure that the file is proper by checking it out again.
cd ~/adsb-receiver && git checkout -- build/portal/graphs/make-collectd-graphs.sh

Make sure that the files dump1090_aircraft-recent.rrd and dump1090_messages-local_accepted.rrd exist.
ls -l /var/lib/collectd/rrd/localhost/

Backup then remove the to files mentioned above so new ones can be made in case the originals are corrupt. You can restore these by copying them back to their original location of this does not solve anything.
mkdir ~/backups
sudo /etc/init.d/collectd stop
sudo mv /var/lib/collectd/rrd/localhost/dump1090_aircraft-recent.rrd 
sudo mv /var/lib/collectd/rrd/localhost/dump1090_messages-local_accepted.rrd
sudo /etc/init.d/collectd start

**Comment by Calimerorulez** [comment] 2016-10-19 13:39
Sadly that does not work...

Manually running the generation command:

sudo bash /home/radar/adsb-receiver/build/portal/graphs/make-collectd-graphs.sh 24h

Still gives me the following error:

ERROR: don't understand 'rate-provisional,0,IF'

Which corresponds to "CDEF:rate=aircrafts,0,GT,rate-provisional,0,IF" in build/portal/graphs/make-collectd-graphs.sh on line 55.

**Comment by ForestFeather** [comment] 2016-10-25 15:27
Will say that I also have this issue - fresh install, 2.4.0.  I also see it on the Disk I/O IOPS and Disk I/O Bandwidth charts.

**Comment by jprochazka** [comment] 2016-11-30 19:13
What type of device are your setups running? If Raspberry Pi is there an external drive such as a USB hard drive or stick in place?

**Comment by ForestFeather** [comment] 2016-11-30 19:32
In at least my case, I am running a full laptop (older model, but still a full laptop) with 250GB HDD.  I can readily supply full specs.

**Comment by jprochazka** [comment] 2016-11-30 19:37
No that's all I needed I know the problem now. The device is not being set in /etc/collectd/collectd.conf. A work around is to open this file and look for the following line:

`	Disk "mmcblk0"`

In most cases where an SD card is not being used this should look like so:

`	Disk "sda"`

Changing this line should have you up and running. Look for a permanent fix to be committed soon.

**Comment by ForestFeather** [comment] 2016-11-30 19:57
I made both those changes in my local install and I can confirm that they do work as intended for disk operations!  Still don't have working aircraft message rates chart, however.

**Comment by jprochazka** [comment] 2016-11-30 20:44
Could you provide the Linux distro you are using so I can try to recreate this issue?

**Comment by ForestFeather** [comment] 2016-11-30 20:48
outputs of lsb_release -a:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

**Comment by ForestFeather** [comment] 2016-11-30 20:55
For reference, here is the output of a manual run of make-collectd-graphs.sh:
$ > sudo bash ./make-collectd-graphs.sh 24h
[sudo] password for ********: 
4154 (process ID) old priority 0, new priority 5
577x298
ERROR: don't understand 'rate-provisional,0,IF'
577x298
577x298
1107x284
577x298
577x298
577x298
577x298
577x298
577x298
577x298
577x298
577x298
1107x284
577x298
577x298
577x298
577x298

**Comment by jprochazka** [comment] 2016-12-01 18:17
Thanks for the information. Using the information you supplied pertaining to the OS you are using I was able to recreate and fix this issue. An updated make-collectd-graphs.sh has been committed to the master branch which should resolve this issue. running the following command should be all you need to do in order to pull down the fixed file.
```
cd ~/ && git pull
```
commit b4f1ed361cf51c3cd93f1c3088c78e28de7b199e

**Closed** 2016-12-01 18:18 UTC
Labels: bug

**Comment by skaw847** [comment] 2018-05-06 16:17
Hi,

i am using the 2.6.2 image with dump1090-mutability in conjunction with beast-splitter since i am using a mode-s beast..

things are working so far, local dump1090 map is working and showing a message rate, flightaware is working as well, getting mlat results back etc.

BUT..somehow the performance graphs 

Message Rate
Message Rate (Trailing)
Signal Level
Aircraft Message Rate 

are not working. All i get ist a 404 error. I have a parallel installation with an FA ProstickPlus with the same image and also Dump1090-Mutability and the graphs are working on that receiver.

Are there any issues with the graphs and beast-splitter/Mode-S Beast? At least the message rate gets to dump1090, since i can see it on the live map?!

**Comment by orionjb2001** [comment] 2018-05-06 19:12
Skaw847, can I direct you to this site:  https://www.adsbreceiver.net/forums/ re above question.  Your more likely to get some sort of an answer, perhaps.  The developer last entered this comment 2 years ago.  I may be doing the same thing shortly with a mode S receiver, I am curious as to any info using beast splitter  and these scripts.
